In [3]:
import numpy as np

In [4]:
B=np.array([[[11,12,13],[14,15,16],[17,18,19]],[[91,92,93],[94,95,96],[97,98,99]]])

In [5]:
B

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[91, 92, 93],
        [94, 95, 96],
        [97, 98, 99]]])

In [6]:
np.transpose(B)

array([[[11, 91],
        [14, 94],
        [17, 97]],

       [[12, 92],
        [15, 95],
        [18, 98]],

       [[13, 93],
        [16, 96],
        [19, 99]]])

In [ ]:
'''dim0不变, dim1和dim2做tranpose'''

In [7]:
C=np.transpose(B,(0,2,1))

In [8]:
C

array([[[11, 14, 17],
        [12, 15, 18],
        [13, 16, 19]],

       [[91, 94, 97],
        [92, 95, 98],
        [93, 96, 99]]])

In [9]:
D=np.transpose(B,(1,0,2))

In [10]:
D

array([[[11, 12, 13],
        [91, 92, 93]],

       [[14, 15, 16],
        [94, 95, 96]],

       [[17, 18, 19],
        [97, 98, 99]]])

In [ ]:
## 高维度时 np.transpose
## https://blog.csdn.net/wgx571859177/article/details/80999133